name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

# Cancel old jobs if new jobs start
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install pytest
        run: python -m pip install -U pytest
      - name: Install backend requirements
        run: python -m pip install -r backend/requirements.txt
      - name: Run pytest
        run: pytest backend/
